
proxy:
  saml:
    idp-metadata-url: https://login.microsoftonline.com/b15748f8-c407-4b7e-a418-dd0eb048bb3f/FederationMetadata/2007-06/FederationMetadata.xml
    app-entity-id: api://59932e2c-8f3b-4c36-bd10-593758d8209a
    app-base-url: https://shinyproxy.potentia.cloud
    roles-attribute: http://schemas.microsoft.com/ws/2008/06/identity/claims/role
  port: 8080
  container-backend: kubernetes
  kubernetes:
    internal-networking: true
    url: http://localhost:8001
    image-pull-secret: acr-auth
  specs:
  - id: 01_hello
    display-name: Hello Application
    description: Application which demonstrates the basics of a Shiny app
    container-cmd: ["R", "-e", "shinyproxy::run_01_hello()"]
    container-image: openanalytics/shinyproxy-demo
  - id: 06_tabsets
    container-cmd: ["R", "-e", "shinyproxy::run_06_tabsets()"]
    container-image: openanalytics/shinyproxy-demo

logging:
  file:
    shinyproxy.log
    
server:
  useForwardHeaders: true
